package berezkindv.tests;

import berezkindv.helpers.DriverUtils;
import com.codeborne.selenide.conditions.Text;
import io.qameta.allure.Description;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("twitch.tvUiTests")
    void generatedTest() {
        step("'Открываем страницу: 'https://www.twitch.tv/'", () -> {
            open("https://www.twitch.tv/");
        });

        step("Нажимаем кнопку 'Войти'", () -> {
            $("button[data-test-selector='anon-user-menu__login-button']").click();
        });

        step("Проверяем открытие формы логина", () -> {
            $("div[data-a-target='passport-modal']").$("#modal-root-header").shouldHave(text("Войти в Twitch"));
        });

        step("check login form is open", () -> {
            step("// todo: just add selenium action");
        });

        step("login", () -> {
            step("// todo: just add selenium action");
        });

        step("check logged in", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Disabled
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.twitch.tv/'", () ->
            open("https://www.twitch.tv/"));

        step("Page title should have text 'Twitch'", () -> {
            String expectedTitle = "Twitch";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Disabled
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.twitch.tv/'", () ->
            open("https://www.twitch.tv/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}